### ISSUE TITLE
ERROR: Expected newline or end of document after a statement

### ISSUE THREAD

**Issue by rajtilakjee** [ysawa0/create-python-app#9]
I tried creating a test project using the tool and ran into this error (attaching a screenshot for better perspective):

`Expected newline or end of document after a statement`

![image](https://github.com/ysawa0/create-python-app/assets/117737297/682d97d4-fbcb-445b-a650-80049524e71b)

**Comment by ysawa0** [comment]
Nice catch, believe it's due to Windows using \r\n for EOF. Working on a fix but needs more testing

**Comment by ysawa0** [comment]
Actually, this may be a bug in poetry https://github.com/python-poetry/poetry/issues/7885 @rajtilakjee could you try upgrading and see if that fixes it

**Comment by rajtilakjee** [comment]
@ysawa0 you are right, I updated poetry to 1.7.0 and it worked like a charm.
